version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/YOUR_DIRECTORY/ # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/python:3.6.4 # ...with this image as the primary container
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run: sudo pip install --upgrade pip
      - run: sudo pip install -r requirements.txt
      #- run: python -m unittest discover
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
  # deploy:
  #   docker:
  #     - image: buildpack-deps:trusty
  #   steps:
  #     - checkout
  #     - run:
  #         name: Deploy Master to Heroku
  #         command: |
  #           git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master
